version: '3'

volumes:
  prometheus_data: {}

services:
  prometheus-server:
    image: prom/prometheus:latest
    container_name: prometheus-server
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ${PWD}/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--storage.tsdb.retention.time=30d'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'

  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    restart: always
    ports:
      - 9116:9116
    volumes:
      - ${PWD}/snmp-generator/snmp.yml:/etc/snmp_exporter/snmp.yml
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
      - '--log.level=debug'
