version: '3'

volumes:
  prometheus_data: {}

services:
  prometheus-server:
    image: prom/prometheus:latest
    container_name: prometheus-server
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ${PWD}/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--storage.tsdb.retention.time=30d'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'

  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    restart: always
    ports:
      - 9116:9116
    volumes:
      - ${PWD}/snmp-generator/snmp.yml:/etc/snmp_exporter/snmp.yml
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
      - '--log.level=debug'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - 9100:9100
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
