global:
  scrape_interval:     30s
  scrape_timeout:      15s

  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval:     15s
    scrape_timeout:      10s
    static_configs:
    - targets: ['10.1.3.96:9090']

  - job_name: 'juniper_srx'
    scrape_interval:     30s
    scrape_timeout:      20s
    static_configs:
      - targets:
        - 10.1.2.1
    metrics_path: /snmp
    params:
      module: [ juniper_srx ]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.1.3.96:9116 

  - job_name: 'juniper_ex'
    scrape_interval:     30s
    scrape_timeout:      20s
    static_configs:
      - targets:
        - 10.1.2.2
        - 10.1.3.1
    metrics_path: /snmp
    params:
      module: [ juniper_ex ]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.1.3.96:9116 
